### ISSUE TITLE
Need moar guidance

### ISSUE THREAD

**Issue by alcoholnapkin3** [alcoholnapkin3/fluttering_cookie#1]
Konnichiwa, file "guidance.txt" doesn't have enough guidance. We are lost and we need guidance.
One might find guidance at https://randomwordgenerator.com/sentence.php

**Comment by Yuktopus** [comment]
Flying fish flew by the space station.

**Comment by alcoholnapkin3** [comment]
> Flying fish flew by the space station.

Dan ate the clouds like cotton candy.

**Comment by alcoholnapkin3** [comment]
Being unacquainted with the chief raccoon was harming his prospects for promotion.
